### PR TITLE
Create README.MD

### PR DESCRIPTION
**Pull request by LuisRodriguezLD**
Added my example on Tags using Firebase

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for the pull request! Though, it seems you've created a new README.md file? Maybe you could try to open a new pull request or fix this one?

**Comment by LuisRodriguezLD** [comment]
I am sorry. This is my first time actually posting something on GitHub. I will try to open a new one. Thank you!

**Comment by vinkla** [comment]
@offwings no worries! Let me know if you need any help.

**Comment by LuisRodriguezLD** [comment]
I added a new pull request. It's ready to be reviewed

**Comment by vinkla** [comment]
Okay, I'm closing this then.

**Pull request closed without merging**
