### PR TITLE
Added NPM modules link

### PR DESCRIPTION
**Pull request by bentstamnes**

### CODE REVIEW

**Comment by vinkla** [comment]
Wow! This is really awesome. Does Fuse support all kinds of libraries? 

Thanks for the PR!

**Comment by bentstamnes** [comment]
You'd have to ask @bolav (https://github.com/bolav) about that, but I would imagine _no_, since a bunch of the npm modules/libraries probably use the DOM in some way, and that won't fly with Fuse (since there is no DOM :)

**Comment by vinkla** [comment]
Okay, but those that doesn't will work then?

**Comment by bentstamnes** [comment]
As I understand it, it's still in early/experimental stages, but @bolav probably has a better guesstimate than me :)

**Comment by bolav** [comment]
There is no DOM in any npm modules. I haven't gotten any to work out of the box yet, but a lot will work with just a little bit of tuning.

**Comment by vinkla** [comment]
Okay, let us know when you do then we can play around with it! I think NPM and the Node community will definitely help Fuse get bigger, better, faster and stronger.

**Comment by bolav** [comment]
If you have a NPM module that you think we need I can test it, and show you the result.

**Comment by bolav** [comment]
Look here for instance: https://github.com/bolav/fuse-example-using-socketio

**Comment by vinkla** [comment]
Thanks for sharing. Don't know any package per say but since the Node community is so modular a lot of things can be simplified by pulling in a package for a small task. I think Fuse would really benefit of a super powerful NPM integration. That would make the transition to Fuse for web-developers super fast. They already know the tools and can just start building.

**Pull request merged**
